title: Land Surveyors Board
title-abbreviated: Title
description: >- # this means to ignore newlines until "baseurl:"
  Description
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Resource Room and Pagination
paginate: 12

# Homepage sections
homepage_hero_i_want_to: false
homepage_resources: true

# Feedback Form URL
feedback_form_url: "https://www.mlaw.gov.sg/eservices/enquiry/"

# FAQ URL
faq_url: "https://va.ecitizen.gov.sg/cfp/customerPages/mlaw/explorefaq.aspx"
faq_url_external: true

# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"

collections:
  about-us:
    output: true
  find-a-surveyor:
    output: true
  register-to-be-a-surveyor:
    output: true
  guidelines-and-policies:
    output: true
  forms:
    output: true
  circular:
    output: true

future: true
resources_name: "notices-and-announcements"
